version: "3.1"

services:
  oidc-fastapi-server:
    build: 
      context: .
      dockerfile: ./dockerfiles/Dockerfile.acc-oidc-fastapi
    ports:
      - "8000:8000"
    depends_on:
      - oidc-server-db
      - accpy-oidc-agent
    volumes:
      - ./oidc_server/app:/app/app
    networks:
      - oidc
#  oidc-fastapi-server:
#    build: .
#    environment:
#      OIDC_DB_USER: OIDC_DB_USER
#      OIDC_DB_PASSWORD: OIDC_PASSWORD
#      OIDC_DB_NAME: OIDC
#      OIDC_DB_PORT: 5432
#      ACAPY_ADMIN_PORT: 3021
#      ACAPY_TRANSPORT_PORT: 3020
##      DJANGO_SETTINGS_MODULE: ${DJANGO_SETTINGS_MODULE}
##      SECRET_KEY: ${SECRET_KEY}
##      SITE_URL: ${SITE_URL}
##      DEBUG: ${DEBUG}
##      OIDC_RP_PROVIDER_ENDPOINT: ${OIDC_RP_PROVIDER_ENDPOINT}
##      OIDC_RP_CLIENT_ID: ${OIDC_RP_CLIENT_ID}
##      OIDC_RP_CLIENT_SECRET: ${OIDC_RP_CLIENT_SECRET}
##      OIDC_RP_SCOPES: ${OIDC_RP_SCOPES}
##      VC_AUTHN_PRES_REQ_CONF_ID: ${VC_AUTHN_PRES_REQ_CONF_ID}
##      NGROK_AGENT_URL: ${NGROK_AGENT_URL}
##      AUTH_URL: ${AUTH_URL}
#    networks:
#      - oidc-server-db
#    ports:
#      - 5000:8080
#    depends_on:
#      - oidc-server-db
#      - accpy-oidc-agent
#    volumes:
#      - ./:/code
      
  oidc-server-db:
    image: registry.access.redhat.com/rhscl/postgresql-10-rhel7:latest
    environment:
      POSTGRESQL_USER: OIDC_DB_USER
      POSTGRESQL_PASSWORD: OIDC_PASSWORD
      POSTGRESQL_DATABASE: OIDC
    ports:
      - 5433:5432
    volumes:
      - db-volume:/var/lib/pgsql/data
    networks:
      - oidc
      
  accpy-oidc-wallet-db:
    image: postgres:11
    container_name: accpy-oidc-wallet-db
    command: postgres -c listen_addresses='*'
    env_file:
      - .env
    volumes:
      - db-volume:/var/lib/pgsql/data
      - ./resources/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - oidc
    tty: true
  ngrok-accpy-oidc:
    image: wernight/ngrok
    env_file:
      - .env
    command: ngrok http accpy-oidc-agent:3020 --log stdout
    networks:
      - oidc
  accpy-oidc-agent:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.agent
    image: bcgovimages/aries-cloudagent:py36-1.15-1_0.6.0
    env_file:
      - .env
    ports:
      - 7021:3021
      - 7020:3020
    networks:
      - oidc

volumes:
  db-volume:

networks:
  oidc:
