version: "3.1"

services:
  web:
    build: 
      context: .
      dockerfile: ./dockerfiles/Dockerfile.acc-oicd-fastapi
    ports:
      - "8000:8000"
    networks:
      - oidc-server-db
  oidc-fastapi-server:
    build: .
    environment:
      OIDC_DB_USER: ${POSTGRESQL_USER}
      OIDC_DB_PASSWORD: ${POSTGRESQL_PASSWORD}
      OIDC_DB_NAME: ${POSTGRESQL_DATABASE}
      OIDC_DB_PORT: 5432
      ACAPY_ADMIN_PORT: ${AGENT_ADMIN_PORT}
      ACAPY_TRANSPORT_PORT: ${AGENT_HTTP_PORT}
      DJANGO_SETTINGS_MODULE: ${DJANGO_SETTINGS_MODULE}
      SECRET_KEY: ${SECRET_KEY}
      SITE_URL: ${SITE_URL}
      DEBUG: ${DEBUG}
      OIDC_RP_PROVIDER_ENDPOINT: ${OIDC_RP_PROVIDER_ENDPOINT}
      OIDC_RP_CLIENT_ID: ${OIDC_RP_CLIENT_ID}
      OIDC_RP_CLIENT_SECRET: ${OIDC_RP_CLIENT_SECRET}
      OIDC_RP_SCOPES: ${OIDC_RP_SCOPES}
      VC_AUTHN_PRES_REQ_CONF_ID: ${VC_AUTHN_PRES_REQ_CONF_ID}
      NGROK_AGENT_URL: ${NGROK_AGENT_URL}
      AUTH_URL: ${AUTH_URL}
    networks:
      - oidc-server-db
    ports:
      - 5000:8080
    depends_on:
      - oidc-db
      - aca-py
    volumes:
      - ./:/code
      
  oidc-server-db:
    image: registry.access.redhat.com/rhscl/postgresql-10-rhel7:latest
    env_file:
      - .env
    environment:
      POSTGRESQL_USER: ${OIDC_POSTGRESQL_USER}
      POSTGRESQL_PASSWORD: ${OIDC_POSTGRESQL_PASSWORD}
      POSTGRESQL_DATABASE: ${OIDC_POSTGRESQL_DATABASE}
    ports:
      - ${EXPOSED_DATABASE_SERVICE_PORT}:5432
    volumes:
      - db-volume:/var/lib/pgsql/data
    networks:
      - oidc
      
  accpy-oidc-wallet-db:
    image: postgres:11
    container_name: accpy-oidc-wallet-db
    command: postgres -c listen_addresses='*'
    env_file:
      - .env
    volumes:
      - ./resources/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - oidc
    tty: true
  ngrok-accpy-oidc:
    image: wernight/ngrok
    env_file:
      - .env
    command: ngrok http accpy-oidc-agent:3020 --log stdout
    networks:
      - oidc
  accpy-oidc-agent:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.agent
    image: bcgovimages/aries-cloudagent:py36-1.15-1_0.6.0
    env_file:
      - .env
    ports:
      - 7021:3021
      - 7020:3020
    networks:
      - oidc

volumes:
  db-volume:

networks:
  oidc:
