FROM tiangolo/uvicorn-gunicorn-fastapi:python3.7



WORKDIR /app

COPY oidc_server/ /app

RUN cd /app && pip install -r requirements.txt

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
